FROM node:22-alpine AS builder

WORKDIR /app

COPY broadcast_frontend/package*.json ./

RUN npm install

COPY broadcast_frontend/. .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY broadcast_frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
